### PR TITLE
Move the API definitions to a new package, `CheckedArithmeticCore`

### LINKED ISSUE #4: Supporting `div` and `%`
I think `div` and `%` should be interpreted as aliases for `÷` and `rem`.
```julia
julia> @macroexpand(@checked typemax(UInt) ÷ -1)
:(Base.Checked.checked_div(typemax(UInt), -1))

julia> @macroexpand(@checked div(typemax(UInt), -1))
:(div(typemax(UInt), -1))

julia> @macroexpand(@checked typemax(UInt) % -1)
:(typemax(UInt) % -1)

julia> @macroexpand(@checked rem(typemax(UInt), -1))
:(Base.Checked.checked_rem(typemax(UInt), -1))
```

### LINKED ISSUE #6: Separation to `CheckedArithmeticCore`
From the beginning of this package, I have believed that the dependencies on this package would bring in trouble. (cf. https://github.com/JuliaMath/FixedPointNumbers.jl/pull/146#issuecomment-560099028)

The "features" provided by `CheckedArithmetic` are on a higher level than packages that provide types like `FixedPointNumbers`. The dependency of a low-level package on a high-level package leads to roughly two problems.
1. Keeping up with compatibility
Until `CheckedArithmetic` reaches v1.0, packages that provide numeric types are implicitly required to keep up with the new version when there are changes to the implementation or functionality of `CheckedArithmetic`, even if they do not break the existing API.

2. Weight limit of `CheckedArithmetic`
If `CheckedArithmetic` is "heavy", it affects all users of the package which (indirectly) depend on the package providing the numeric types. Therefore, `CheckedArithmetic` is implicitly required to be lightweight. I suspect that the `Cassette`'s injection feature could be useful in "end-user" code, but I don't think it is a good idea for packages which provide numeric types to be dependent on `Cassette`.

I would like to make the `CheckedArithmetic` support not only `checked` arithmetic, but also `wrapping` and `saturating` arithmetic. (cf. https://github.com/JuliaMath/FixedPointNumbers.jl/issues/152#issuecomment-647113657) And in the future, I would like to integrate the features into `Base`(`Base.Checked`). With this perspective, I think it would be beneficial to make the APIs and the implementations separate.

### PR DESCRIPTION
**Pull request by kimikage**
Closes #6 

This also add support for `div` and `%` in `@checked`. (Fixes #4)
This switches the CI from Travis to GitHub Actions, and adds Julia v1 and 32-bit x86 to the test target.

### CODE REVIEW

**Comment by timholy** [comment]
Thanks!

**Comment by kimikage** [comment]
There is still work to be done within CheckedArithmeticCore, but I think we need to register only CheckedArithmeticCore first, as it is a new package and registration will take 3 days.

I don't have any experience with registering a package in a subdirectory, is the following method available?
https://github.com/JuliaRegistries/Registrator.jl#registering-a-package-in-a-subdirectory

**Comment by timholy** [comment]
I've only done it once, for SnoopCompile, and that was before that was available. So no clue, but seems worth trying.

**Comment by kimikage** [comment]
It seems to be working well. It's great.
https://github.com/JuliaRegistries/General/pull/21528

**Pull request merged**
